FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

ENV DEVICE="ALL"
ENV TIMEOUT="3600"
ENV THREADS="100"
ENV BLOCKS="40,256"
ENV OUTPUT_PATH="/output/smacc_output.tsv"

RUN apt-get update -y && apt upgrade -y
RUN apt-get install python3 python3-pip -y
RUN apt-get install git -y
RUN mkdir /output
WORKDIR /Smacc

RUN git clone https://github.com/Baksling/P7-SMAcc.git .

# WORKDIR /Smacc/src2/Cuda/
RUN bash /Smacc/src2/Cuda/compile.sh

CMD ["python3", "/Smacc/Analysis/auto_test_runner.py", \
    "-p", "/Smacc/Cuda/c.out", "-d", "${DEVICE}", \
    "-m", "/Smacc/Cuda/UPPAALXMLParser/XmlFiles/", \
    "-b", "${BLOCKS}", "-t", "${THREADS}", "-o", "${OUTPUT_PATH}",\ 
    "--timeout", "${TIMEOUT}"]