FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

RUN apt-get update -y && apt upgrade -y
RUN apt-get install python3 python3-pip -y
RUN apt-get install git -y

WORKDIR /Smacc

RUN git clone https://github.com/Baksling/P7-SMAcc.git .

WORKDIR /Smacc/src2/Cuda/
RUN bash ./compile.sh